#!/bin/bash

dest="_site"
INDEX="${indexfile}"

for FILE in "${dest}"/*; do
DETAILS="${DETAILS}\
<details>\
<summary>$(basename "${FILE}" | sed 's/.html//')</summary>\
<div>\
$(cat "${FILE}")\
</div>\
</details>"
done

echo "<head><link rel=\"stylesheet\" href=\"style.css\"><link href=\"https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;500&amp;display=swap\" rel=\"stylesheet\"></head>" > "${INDEX}"
echo "${DETAILS}" >> "${INDEX}"
